### ISSUE TITLE
Access rights, information might be incorrect

### ISSUE THREAD

**Issue by benabbottnz** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#10]
On this page: https://docs.typo3.org/m/typo3/tutorial-editors/master/en-us/AccessControl/Login/Index.html you will see a section talking about Access Rights and how you can set a "Members only" page.

If using the "Show at any login" Usergroup, the last sentence in that section claims that you'll be redirected to the home page, but in my experience with both a brand new TYPO3 site, and all my existing sites, TYPO3 will simply 404 if you try to access that page.

Is the documentation wrong, or has that functionality changed since it was written?

I'm having great difficulty figuring out how to redirect a user to either the Home page or the login page when accessing a page with invalid usergroup rights.

**Comment by sypets** [comment]
So you are looking for a way to redirect to a login page if you access a page with access restriction and are not logged in with a user that has access to the page?

Sounds reasonable to me. It appears the documentation may be wrong or at least it does not explain it sufficiently.

I have not been able to get this to work either. I found some solutions that were offered, none of them worked for me right away, but you may want to look there for further hints:

* https://stackoverflow.com/questions/6663228/typo3-404-for-restricted-access-page-instead-of-login-form
* https://docs.typo3.org/c/typo3/cms-felogin/8.7/en-us/Examples/Index.html

I will try to investigate further. This may take a while. Everyone is pretty busy right now getting everything ready for TYPO3 X.

I propose to leave this issue open until it is further investigated and corrected.

BTW, which TYPO3 version do you use?

**Comment by benabbottnz** [comment]
I've been using TYPO3 9.

**Comment by FelHell** [comment]
When trying to access a page that can only be accessed by a usergroup, this error message in TYPO3 9.5 is shown:

![typo3-page-not-found-subsection-not-accessible](https://user-images.githubusercontent.com/43313855/62393780-6ad54280-b56b-11e9-8382-f828e1c13b1f.png)

**Comment by FelHell** [comment]
@benabbottnz In TYPO3 9.5, the error message is generated in https://github.com/TYPO3/TYPO3.CMS/blob/16a8bcabe4d8a33a2bc8556b440ed92af0ee508b/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L1456 and the method `accessDeniedAction` of `\TYPO3\CMS\Frontend\Controller\ErrorController` is called.

You can change the default behaviour by setting a value in the global configuration:
```
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFound_handling'] = 'REDIRECT:https://www.example.com/';
```
For example, this would redirect an unauthenticated frontend user to www.example.com when trying to access a restricted page.

**Comment by FelHell** [comment]
Maybe it makes sense to add a reference to the `pageNotFound_handling` variable to the documentation.
