### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by aksenovaa** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#12]
Hello! I would like to translate this document into Russian (ru_RU). Could you make an appropriate structure?

**Comment by sypets** [comment]
Sorry about the late reply. 

I will open a discussion in #typo3-documentation in Slack. 

In the past we have been reluctant with translations for docs.typo3.org. This is why:

-----------

Our general policy:

Generally we are having a hard time keeping the docs updated and well maintained. We are working hard on this, but the speed of TYPO3 core development and changes is not easy to keep up with.

There is a technical mechanism in place to create and render translations for the docs. For many users, it would be very helpful to have translations. However, our main concern is keeping the translation well maintained and updated. This is already difficult for the English language, may be even more difficult for other languages. This is why we are currently reluctant to create translations.

See also: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/HowToAddTranslation/Index.html

-----

For your specific request:

I would like to offer you an opportunity. Personally, I would love to see the tutorial in more languages - if we can make sure, it will be well maintained and updated in the future. But let me first wait, what is said in the Slack channel. 

In any case, I think the Tutorial should get updated first. Should be ready in 1 or 2 months.

**Comment by sypets** [comment]
See answer from Slack channel:

> We don't need to discourage people and we shouldn't. Instead we can safely encourage people to go ahead with a translation or a similar manual in that language. People can do whatever they like within the limits of the CC or OpenContent license. However, we sadly have to point out, that the docteam has NO manpower for the actual translation or writing. My advice is to start a translation in the form of a TYPO3 extension where that form just servers as a container to hold the documentation. As such it can make use of the serverside rendering chain and it is obvious, that  that documentation is maintained by the extension author(s) and not by the documentation team.

In general, if you have questions about documentation, you can join Slack channel: https://typo3.org/community/teams/documentation

**Comment by susannemoog** [comment]
I'll close this issue now as there has been no further feedback for over a year - if you feel that this is the wrong decision, please don't hesitate to say so.
