### ISSUE TITLE
Change outdated "Creating a contact form" part

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#23]
The form part is completely outdated:
https://docs.typo3.org/m/typo3/tutorial-editors/10.4/en-us/ContentElements/ContactForm/Index.html

Should probably be changed to a small description, what forms are and then link to the integrator guide of ext:form.

**Comment by sypets** [comment]
@IndyIndyIndy Thank you very much for your efforts.

The "Tuturial for Editors" has received little changes in the past 2 years. I reviewed the "Getting Started Tutorial" for version 9 meaning an entire review and udate of all pages (including screenshots if necessary). I think the TfE could use something similar - a systematic review. 

I had planned to do that but the reason I didn't was that I wanted to finish the boilerplate icons and guidelines for images first. There are lots of images and I don't know if it is a good idea to keep using the orange arrow which uses a different color from what is in the styleguide (this has been raised multiple times and might be solved by now). 

Anyway, any effort is welcome :)

**Comment by IndyIndyIndy** [comment]
I wanted to change the screenshots as well, but noticed that my recent MacBook here is probably not the best tool for that. Because of the pretty high resolution, the cropped screenshot parts have very large dimensions and probably won't look that great when they are scaled down later. ;) I think I will need to boot up an older device later for creating screenshots with a standard 1080p resolution, but I'll create some github issues for now.

**Comment by flicstar** [comment]
I have re-written this page. It is currently in the draft version: https://docs.typo3.org/m/typo3/tutorial-editors/draft/en-us/ContentElements/ContactForm/Index.html
I have worked on the whole manual, and don't yet know how to approach merging the changes. Will get some help from Docs team to do that.
