### ISSUE TITLE
Change outdated "Adding Multiple Pages at Once"

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#24]
https://docs.typo3.org/m/typo3/tutorial-editors/10.4/en-us/Pages/AddingMultiple/Index.html

The functions module no longer exists. - The same functionality is now found in the page tree context menu, so text and screenshots have to be updated.

**Comment by flicstar** [comment]
I've re-written this page in the draft branch: https://docs.typo3.org/m/typo3/tutorial-editors/draft/en-us/Pages/AddingMultiple/Index.html
Not yet merged.
