### ISSUE TITLE
Update screenshots to 10.4

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#25]
Screenshots in the documentation are mostly from TYPO3 7.6, current is 10.4. Most of them are still viable, but there are some cosmetic changes, most notably the changes done for checkbox elements, screenshots of old rtehtmlarea... but rather low priority.

**Comment by flicstar** [comment]
I have looked at each page in the manual, and updated screenshots as per version 10.4. Not yet merged, still in draft branch.
