### ISSUE TITLE
New to Typo3

### ISSUE THREAD

**Issue by pcampagna** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#6]
I inherited a typo three site and it's truly a mess. I am trying to change a simple thing, but i'm on day 2 of not being able to figure it out.

So the tutorials are mostly in German, but trying to reach the first developer has taken a week just to get a password to log in to the backend.  

I am trying to adjust the logo on our homepage, which is squashed. How do I get the the actual code of the site and just set the width of the image to 100%? 

It would've literally taken 20 seconds using dreamweaver. 

When i go to the supposed "template", there is no code anywhere.  Even when I can get some code to show up, I can't edit it?  I'm thinking the backend to do this stuff is not available to me in the program. Since there is an external source for this site, is it possible they didn;t include the ability to see the code. or edit?

I ultimately would love to transfer the entire site to something with much better (English) support and tutorials. I have to figure out how i can do basic stuff before that.

**Comment by sypets** [comment]
This is partially a documentation issue and a support issue. 

But, I assume (hope), by now your questions have been answered or you have moved on. I will answer the question anyway and then close this issue. 

**For support:**

To get support for TYPO3, please see: https://typo3.org/help/ and ask your questions either in the #typo3-cms Slack channel or on StackOverflow.

**About documentation**

Please consider, that TYPO3 is an open source project, which you can use without paying a cent for it. Development and documentation is done by the community, everyone can participate. 

Feedback via issues is important, but it would have been better, if you had provided some concrete examples and links:

* which tutorials did you use, what was missing etc. ?

TYPO3 and dreamweaver are two completely different things. TYPO3 is an enterprise solution for which basic configuring and developing is necessary. It does have a learning curve. In your case, I think the best thing to do first would have been to decide if TYPO3 is a good fit for you. You could also find help for questions like this (or at least a few pointers) in the #typo3-cms channel on Slack. To find out how to register for the Slack workspace, you should also see:  https://typo3.org/help.

There is also a new tutorial which didn't exist yet when you asked. You might find it helpful: 
https://docs.typo3.org/typo3cms/SitePackageTutorial/

You should however read the Getting Started tutorial first:
https://docs.typo3.org/typo3cms/GettingStartedTutorial/

**Comment by sypets** [comment]
P.S. Sorry about the late answer. We usually respond to issues faster, this was somehow overlooked.
