### ISSUE TITLE
Some mistakes in the doc 

### ISSUE THREAD

**Issue by KaiGrosz** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#83]
I found some mistakes in the documentation that I wanted to share with you, hope they are all mistakes :)

1. https://docs.typo3.org/m/typo3/tutorial-editors/main/en-us/Pages/PageProperties/Index.html

![image](https://user-images.githubusercontent.com/38782120/166473742-e4318a06-6196-44fb-b820-12cd0f2b3c54.png)

2. https://docs.typo3.org/m/typo3/tutorial-editors/main/en-us/AccessControl/Login/Index.html

![image](https://user-images.githubusercontent.com/38782120/166474129-2bec47bf-f88f-4129-b09d-11f60339ebf1.png)

3. https://docs.typo3.org/m/typo3/tutorial-editors/main/en-us/ListModule/UsingEffectively/Index.html

![image](https://user-images.githubusercontent.com/38782120/166474499-b48c862b-fa5f-4723-b063-a8e01459dac0.png)

4. https://docs.typo3.org/m/typo3/tutorial-editors/main/en-us/ContentElements/Media/Index.html

![image](https://user-images.githubusercontent.com/38782120/166474611-2893c9f4-3383-42d3-b79a-2c6700bd61f3.png)

Greetings

**Comment by linawolf** [comment]
Thanks for reporting this. I just created a Pull Request. Once that is merged, these should be resolved.
